name: Firmware build

on:
  push:
    branches: [ 'cardputer' ]
  pull_request:
    branches: [ 'cardputer' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      enable_cardputer:
        description: Build Cardputer board
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  build_cardputer:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.enable_cardputer }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        board: [CARDPUTER]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        BOARD: ${{ matrix.board }}
        UPLOADTOKEN: ${{ secrets.UPLOADTOKEN }}
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        make
        ./scripts/ci_upload.sh
    - name: Upload ${{ matrix.board }} build artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: ${{ matrix.board }}
        path: |
          bin/*.bin
          bin/*.uf2
          bin/*.hex
          bin/*.tgz
          bin/*.zip
